### ISSUE TITLE
Missing support for utf-8

### ISSUE THREAD

**Issue by 07pepa** [pydantic/bump-pydantic#82]
It appears that this project does not support utf-8

create file in empty folder with contents

```python
from pydantic import BaseModel

#just some boilerplateClass
class Myclass:
    test:int # this will break parsing >šěěčřžýáíéů
```

causes folowing traceback
```
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\bump_pydantic\main.py", line 106, in visit_class_def
    code = Path(filename).read_text()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 126: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program Files\Python311\Lib\site-packages\bump_pydantic\main.py:70 in main                    │
│                                                                                                  │
│    67 │   │   task = progress.add_task(description="Looking for Pydantic Models...", total=len   │
│    68 │   │   with multiprocessing.Pool() as pool:                                               │
│    69 │   │   │   partial_visit_class_def = functools.partial(visit_class_def, metadata_manage   │
│ ❱  70 │   │   │   for local_scratch in pool.imap_unordered(partial_visit_class_def, files):      │
│    71 │   │   │   │   progress.advance(task)                                                     │
│    72 │   │   │   │   for key, value in local_scratch.items():                                   │
│    73 │   │   │   │   │   scratch.setdefault(key, value).update(value)                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                 console = <console width=154 ColorSystem.TRUECOLOR>                          │ │
│ │                    diff = False                                                              │ │
│ │                 disable = []                                                                 │ │
│ │                   files = ['test.py']                                                        │ │
│ │               files_str = [WindowsPath('test.py')]                                           │ │
│ │                log_file = None                                                               │ │
│ │        metadata_manager = <libcst.metadata.full_repo_manager.FullRepoManager object at       │ │
│ │                           0x000001E4E7AC4490>                                                │ │
│ │                 package = WindowsPath('.')                                                   │ │
│ │ partial_visit_class_def = functools.partial(<function visit_class_def at                     │ │
│ │                           0x000001E4E5FF2C00>,                                               │ │
│ │                           <libcst.metadata.full_repo_manager.FullRepoManager object at       │ │
│ │                           0x000001E4E7AC4490>, WindowsPath('.'))                             │ │
│ │                    pool = <multiprocessing.pool.Pool state=TERMINATE pool_size=16>           │ │
│ │                progress = <rich.progress.Progress object at 0x000001E4E7AC5210>              │ │
│ │               providers = {                                                                  │ │
│ │                           │   <class                                                         │ │
│ │                           'libcst.metadata.name_provider.FullyQualifiedNameProvider'>,       │ │
│ │                           │   <class 'libcst.metadata.scope_provider.ScopeProvider'>         │ │
│ │                           }                                                                  │ │
│ │                 scratch = {}                                                                 │ │
│ │                    task = 0                                                                  │ │
│ │                 version = None                                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Program Files\Python311\Lib\multiprocessing\pool.py:873 in next                               │
│                                                                                                  │
│   870 │   │   success, value = item                                                              │
│   871 │   │   if success:                                                                        │
│   872 │   │   │   return value                                                                   │
│ ❱ 873 │   │   raise value                                                                        │
│   874 │                                                                                          │
│   875 │   __next__ = next                    # XXX                                               │
│   876                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    item = (                                                                                  │ │
│ │           │   False,                                                                         │ │
│ │           │   UnicodeDecodeError('charmap', b'from pydantic import BaseModel\r\n\r\n#just    │ │
│ │           some boilerplateClass\r\nclass Myclass:\r\n    test:int # this will break parsing  │ │
│ │           >\xc5\xa1\xc4\x9b\xc4\x9b\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9… │ │
│ │           126, 127, 'character maps to <undefined>')                                         │ │
│ │           )                                                                                  │ │
│ │    self = <multiprocessing.pool.IMapUnorderedIterator object at 0x000001E4E7AC6DD0>          │ │
│ │ success = False                                                                              │ │
│ │ timeout = None                                                                               │ │
│ │   value = UnicodeDecodeError('charmap', b'from pydantic import BaseModel\r\n\r\n#just some   │ │
│ │           boilerplateClass\r\nclass Myclass:\r\n    test:int # this will break parsing       │ │
│ │           >\xc5\xa1\xc4\x9b\xc4\x9b\xc4\x8d\xc5\x99\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9… │ │
│ │           126, 127, 'character maps to <undefined>')                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 126: character maps to <undefined>
```

this is on windows 10 with python 3.11

**Comment by 07pepa** [comment]
probably fixed by https://github.com/pydantic/bump-pydantic/pull/83
